Makefile
=> Changes as proposed in #14

Makefile
As requested by @Shreeshrii.
Fixes https://github.com/OCR-D/ocrd-train/issues/55
=> Use `_best` as the default for TESSDATA_REPO

Makefile
Replaced four spaces by a tab
when using a starting model  `make training` was breaking because of this (on my machine at least)
=> fixed Makefile training from start model

Makefile, generate_line_box.py
This avoids problems with UTF-8 encoded strings.
=> Use Python3

Makefile, shuffle.py
sort -R depends on OpenSSL and does not work on macOS because of missing named pipes,
so replace it with a well defined pseudo random shuffling Python script.
=> Reproducible shuffling of training data (fix portability issue #85 for macOS)

generate_wordstr_box.py
The line images are cropped and then padded with 10 pixel white border and the new bounding box is used for box file. The cropped images work better for training, leading to faster convergence.
=> Create tesseract WordStr box files for given (line) image text pairs

Makefile, README.md
Added the TESSDATA parameter description to README.md
As per the example at https://github.com/tesseract-ocr/tesstrain/wiki/GT4HistOCR#finetuning-based-on-scriptfraktur
=> Added TESSDATA to README.md

Makefile, README.md
Meanwhile, GT has to be placed in `data/MODEL_NAME-ground_truth`.
This commit fixes the documentation. In addition, the variable
`BUILD_TYPE` is removed to make sure thate the resulting models
are named as requested by the user.
Fixes #134 and #133
=> Drop "BUILD_TYPE" and remove default ground truth directory

Makefile
... so they aren't treated as intermediate files and deleted on cancel or completion
=> mark box files as PRECIOUS

Makefile, README.md
Tesseract can handle most common image formats while the Makefile
only had supported *.tif.
Line images from other Open Source OCR software use *.bin.png or *.nrm.png.
The Makefile now handles these, too, so it is no longer necessary to
convert them to *.tif.
=> Support additional line image formats (*.png, *.bin.png, *.nrm.png)

Makefile
Please enable the `lstm`parameter `target_error_rate` for tesstrain!
To control training flow it's not always best to got for the MAX_ITERATIONS. 
We need also a quality criteria for the model, so it fits a certain mean error rate above the default of value of 0.01 before MAX_ITERATIONS are applied.
=> [app][feat] enable target_error_rate

generate_wordstr_box.py
It is needed for RTL scripts and does not harm for LTR scripts.
=> Always use bidi algorithm

Makefile, README.md
It allows setting the learning rate hyperparameter for the training.
The default value for finetuning is now reduced from 0.001 to 0.0001
because the old default was too large when finetuning starts with
a network which is already rather good.
=> Add new variable LEARNING_RATE

generate_gt_from_box.py, generate_line_box.py, generate_line_syllable_box.py, generate_wordstr_box.py
`*.gt.txt` should contain a single line of transcribed text.
=> generate*.py: raise ValueError if GT is multiline, fix #162

Makefile
Tesstrain comes with quite restrictive assumptions on the structure of the data in the filesystem (`*.{png,tif}` / `*.gt.txt` pairs under `data/NAME-ground-truth` below the tesstrain code). But often one needs more flexibility, for example because
- the data is in a git repo (but so is tesstrain),
- some mountpoints are faster/larger than others, or the data is simply scattered across locations, or
- you want to (re)group data files in certain ways (e.g. clusters of books by age / material / lang / font)
There's a simple technique usually employed to that end: symlinks!
However, (GNU and BSD) `find` by default does not **follow** directories which are merely symlinks. This PR adds the `-L` option so that all `*.gt.txt` files are found below any such (sub)paths.
=> make find follow symbolic links

Makefile
Looks like this is added by mistake recently
=> correct makefile

src/training/tesstrain_utils.py
On Windows, `Path.write_text` converts the newline code(\n) to CRLF, and `lstmtraining` cannot handle CRLF properly, so the `Deserialize header failed` error occurs. https://github.com/tesseract-ocr/tesseract/issues/2456
This pull request changes `tesstrain.py` to use LF newline code when creating `{lang_code}.training_files.txt` (list of lstmf files) even on Windows.
=> Fix CRLF issue on Windows

Makefile
obviously depends on https://github.com/tesseract-ocr/tesseract/pull/3962 as well
=> support training from .raw.png

Makefile
Make would delete the xxx_checkpoint file when being interrupted, to prevent that, a .PRECIOUS rule was added, but the old one didn't prevent deletion if the xxx_checkpoint file didn't exist at the time of the make invocation, because wildcards are resolved at the start.
The other checkpoint files would never get removed by make anyway, since they are not listed as targets.
Therefore, replace the wildcard rule with $(LAST_CHECKPOINT).
=> prevent checkpoint file from being deleted when "make training" is interrupted

.gitignore, Makefile, README.md
Recent releases of Tesseract and Leptonica are available for all major platforms (Linux, MacOS, Windows), so local build rules are more confusing than helpful.
Update also the links to the online documentation.
=> Remove build rules for Tesseract and Leptonica

Makefile
Commit 25b8508f06365de0fe004fa09871e9bda1b56694 introduced a bug which now prevents `charfreq` from working.
Also, it was not necessary to do the make version checks as a dependency with shell invocation; rather, it's simply a matter of using make's conditionals and control functions.
=> fix make detection of version

Makefile, generate_eval_train.py
This decreases dependency on `bc` program and solves the problem with EOL on Windows.
=> Use python script for generating list.eval and list.train.
