tesseract-ocr/tesstrain

Makefile
=> Implement training using existing models

Makefile
=> replace langdata dependence with just radical-stroke.txt file

generate_line_box.py
Used to cause an exception.
Fixes https://github.com/OCR-D/ocrd-train/issues/41
=> Add a test for line emptiness

Makefile, README.md
Add a seed which can be optionally set by the user for sort -R.
=> Reproducible shuffling of training data

Makefile, README.md
=> Add new parameter MAX_ITERATIONS to set the number of iterations

Makefile
=> Sort training data before shuffling to get reproducible order

Makefile, README.md
=> Add new parameter NET_SPEC for the network specification

Makefile, README.md
=> Write more generated files to model specific output directory

generate_line_syllable_box.py
can be modified to support all Indic scripts by adding appropriate Virama definitions.
=> Create box file for syllables for devanagari script

Makefile
... and some smaller changes in Makefile.
=> Sort entries and remove duplicates in all-boxes

Makefile
"traineddata" rule creates a .traineddata file for each checkpoint in the "checkpoints" folder
Resolves #122
=> Added "traineddata" rule to Makefile

README.md
=> Add more documentation for traineddata target

generate_gt_from_box.py
adds feature request in https://github.com/tesseract-ocr/tesstrain/issues/119
=> Generate groundtruth from text2image box files

README.md
As the feature for modifying the network layer got removed (85b5ae8), the README file should be updated accordingly.
=> Update description to match actual code

generate_wordstr_box.py
As per https://github.com/tesseract-ocr/tesstrain/pull/159#issuecomment-615713572
=> Remove trimming of images

Makefile
As per https://github.com/tesseract-ocr/tesstrain/pull/159#issuecomment-615713572
=> Change Default psm to 13 in Makefile

Makefile
This pull request would fix the feature request issue #89 .
=> Add three new make clean* targets to clean up box, lstmf, output.

Makefile
See https://github.com/tesseract-ocr/tesstrain/issues/172#issuecomment-655246018
For large amount of training data, the current implementation hangs at times.
=> Concatenate with newline for all-gt , remove sort uniq

src/training/tesstrain_utils.py
Porting from tesstrain.sh https://github.com/tesseract-ocr/tesseract/pull/2743
Fix #247
=> Add --ptsize option to tesstrain.py

generate_gt_from_box.py
by using a control character (pretty unlikely to be emitted by text2image or anyone else) instead
=> avoid destroying Greek lambda

count_chars.py
As discussed in https://github.com/tesseract-ocr/tesstrain/pull/235#discussion_r1517037975_ .
Would a pull request from myself be sufficient here, or would it be preferable to add some language about this contribution being under the Apache-2.0 license?
=> contributing count_chars.py utility

src/tesstrain/language_specific.py
=> Fix exposures parameter handling
